In [ ]:
import numpy as np

grid = np.zeros((3, 3))

grid[0, 0] = 1
grid[0, 1] = 2
grid[0, 2] = 3
grid[1, 0] = 0
grid[1, 1] = 4
grid[1, 2] = 5
grid[2, 0] = 6
grid[2, 1] = 7
grid[2, 2] = 8

start = (0, 0)
end = (3, 3)

goal_state = (1, 2, 3,
              4, 5, 6,
              7, 8, 0)

print(grid)
print(f"Start point: {start}")
print(f"End point: {end}")

[[1. 2. 3.]
 [0. 4. 5.]
 [6. 7. 8.]]
Start point: (0, 0)
End point: (3, 3)


In [ ]:
import heapq

def manhattan_distance(state, goal):
    distance = 0
    for i, value in enumerate(state):
        if value != 0:
            goal_index = goal.index(value)
            x1, y1 = divmod(i, 3)
            x2, y2 = divmod(goal_index, 3)
            distance += abs(x1 - x2) + abs(y1 - y2)
    return distance

def get_neighbors(state):
    neighbors = []
    zero_index = state.index(0)
    x, y = divmod(zero_index, 3)

    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # up, down, left, right
    for dx, dy in moves:
        nx, ny = x + dx, y + dy
        if 0 <= nx < 3 and 0 <= ny < 3:
            new_index = nx * 3 + ny
            new_state = list(state)
            new_state[zero_index], new_state[new_index] = new_state[new_index], new_state[zero_index]
            neighbors.append(tuple(new_state))
    return neighbors

def astar(start, goal):
    open_set = []
    heapq.heappush(open_set, (manhattan_distance(start, goal), start))

    came_from = {}
    g_cost = {start: 0}
    f_cost = {start: manhattan_distance(start, goal)}

    while open_set:
        _, current = heapq.heappop(open_set)

        if current == goal:
            path = []
            while current in came_from:
                path.append(current)
                current = came_from[current]
            path.append(start)
            return path[::-1]

        for neighbor in get_neighbors(current):
            tentative_g = g_cost[current] + 1
            if neighbor not in g_cost or tentative_g < g_cost[neighbor]:
                g_cost[neighbor] = tentative_g
                f_cost[neighbor] = tentative_g + manhattan_distance(neighbor, goal)
                heapq.heappush(open_set, (f_cost[neighbor], neighbor))
                came_from[neighbor] = current
    return None


start_state = (1, 2, 3, 0, 4, 5, 6, 7, 8)
goal_state = (1, 2, 3, 4, 5, 6, 7, 8, 0)

In [ ]:
solution_path = astar(start_state, goal_state)

if solution_path:
    print(f"Solution found in {len(solution_path)-1} moves:")
    for step in solution_path:
        print(step[0:3])
        print(step[3:6])
        print(step[6:9])
        print()
else:
    print("No solution found.")


Solution found in 15 moves:
(1, 2, 3)
(0, 4, 5)
(6, 7, 8)

(1, 2, 3)
(4, 0, 5)
(6, 7, 8)

(1, 2, 3)
(4, 5, 0)
(6, 7, 8)

(1, 2, 3)
(4, 5, 8)
(6, 7, 0)

(1, 2, 3)
(4, 5, 8)
(6, 0, 7)

(1, 2, 3)
(4, 5, 8)
(0, 6, 7)

(1, 2, 3)
(0, 5, 8)
(4, 6, 7)

(1, 2, 3)
(5, 0, 8)
(4, 6, 7)

(1, 2, 3)
(5, 6, 8)
(4, 0, 7)

(1, 2, 3)
(5, 6, 8)
(4, 7, 0)

(1, 2, 3)
(5, 6, 0)
(4, 7, 8)

(1, 2, 3)
(5, 0, 6)
(4, 7, 8)

(1, 2, 3)
(0, 5, 6)
(4, 7, 8)

(1, 2, 3)
(4, 5, 6)
(0, 7, 8)

(1, 2, 3)
(4, 5, 6)
(7, 0, 8)

(1, 2, 3)
(4, 5, 6)
(7, 8, 0)

